[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Leader's Guide to Artificial Intelligence: How to Incorporate Intelligent Technologies into Your Organization"
